kind = "web"
previewPath = "/"
title = "Smart Mbarara"
version = "1.0.0"
id = "artifacts/smart-mbarara"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20584

[services.development]
run = "pnpm --filter @workspace/smart-mbarara run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smart-mbarara", "run", "build" ]
publicDir = "artifacts/smart-mbarara/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20584"
BASE_PATH = "/"
